// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SYS.Models;

namespace SYS.Migrations
{
    [DbContext(typeof(contextclass))]
    [Migration("20210519075111_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SYS.Models.Airplane", b =>
                {
                    b.Property<int>("AirplaneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip_avion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AirplaneID");

                    b.ToTable("Airplanes");
                });

            modelBuilder.Entity("SYS.Models.Flight", b =>
                {
                    b.Property<int>("FlightID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AirplaneID")
                        .HasColumnType("int");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.HasKey("FlightID");

                    b.HasIndex("AirplaneID");

                    b.HasIndex("ReservationID");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("SYS.Models.FlightReport", b =>
                {
                    b.Property<int>("FlightReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("FlightReportID");

                    b.HasIndex("UserID");

                    b.ToTable("FlightReports");
                });

            modelBuilder.Entity("SYS.Models.FlightType", b =>
                {
                    b.Property<int>("FLightTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AirplaneID")
                        .HasColumnType("int");

                    b.Property<int>("Nr_Locuri")
                        .HasColumnType("int");

                    b.Property<string>("Ora_plecare")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Ora_sosire")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Plecare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sosire")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FLightTypeID");

                    b.HasIndex("AirplaneID");

                    b.ToTable("FlightTypes");
                });

            modelBuilder.Entity("SYS.Models.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Data_plata")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("ReservationID")
                        .HasColumnType("int");

                    b.Property<string>("Tip_plata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("PaymentID");

                    b.HasIndex("ReservationID");

                    b.HasIndex("UserID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SYS.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Clasa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("ReservationID");

                    b.HasIndex("UserID");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("SYS.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Data_nastere")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("E_mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nr_tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Nume")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SYS.Models.Flight", b =>
                {
                    b.HasOne("SYS.Models.Airplane", "airplane")
                        .WithMany()
                        .HasForeignKey("AirplaneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SYS.Models.Reservation", "reservation")
                        .WithMany()
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("airplane");

                    b.Navigation("reservation");
                });

            modelBuilder.Entity("SYS.Models.FlightReport", b =>
                {
                    b.HasOne("SYS.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("SYS.Models.FlightType", b =>
                {
                    b.HasOne("SYS.Models.Airplane", "airplane")
                        .WithMany()
                        .HasForeignKey("AirplaneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("airplane");
                });

            modelBuilder.Entity("SYS.Models.Payment", b =>
                {
                    b.HasOne("SYS.Models.Reservation", "reservation")
                        .WithMany()
                        .HasForeignKey("ReservationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SYS.Models.User", "user")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("reservation");

                    b.Navigation("user");
                });

            modelBuilder.Entity("SYS.Models.Reservation", b =>
                {
                    b.HasOne("SYS.Models.User", "userid")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userid");
                });
#pragma warning restore 612, 618
        }
    }
}
